language: php
dist: trusty
php:
  - "7.1"
  - "7.2"
  - "7.3"

addons:
  sauce_connect: true

before_script: ./.ci/before_script.sh
script: "vendor/bin/phpunit --verbose Tests"
after_script: ./.ci/after_script.sh
