version: "3"

services:
  web:
    image: nginx
    hostname: web
    ports:
      - "8080:80"
    networks:
      - zalenium
    volumes:
      - ./selenium-1-tests:/usr/share/nginx/html
    restart: always

  zalenium:
    image: dosel/zalenium
    hostname: zalenium
    labels:
      - "de.zalando.gridRole=hub" # important for us to identify the node which runs zalenium hub
    ports:
      - "4444:4444"
    networks:
      - zalenium
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PULL_SELENIUM_IMAGE=true
      - ZALENIUM_PROXY_CLEANUP_TIMEOUT=1800
    # Use version pinning as workaround for: https://github.com/elgalu/docker-selenium/issues/327
    command: ["start", "--seleniumImageName", "elgalu/selenium:3.141.59-p14", "--videoRecordingEnabled", "false"]
    restart: unless-stopped

networks:
  zalenium:
    driver: bridge
